window.meetwayEuropeCities = [
  ["Amsterdam", "Nederland"], ["Rotterdam", "Nederland"], ["Den Haag", "Nederland"], ["Utrecht", "Nederland"], ["Eindhoven", "Nederland"], ["Groningen", "Nederland"], ["Maastricht", "Nederland"], ["Tilburg", "Nederland"], ["Almere", "Nederland"], ["Breda", "Nederland"], ["Nijmegen", "Nederland"], ["Enschede", "Nederland"], ["Haarlem", "Nederland"], ["Arnhem", "Nederland"], ["Amersfoort", "Nederland"], ["Apeldoorn", "Nederland"], ["Zwolle", "Nederland"], ["Leiden", "Nederland"], ["Dordrecht", "Nederland"], ["Zoetermeer", "Nederland"], ["Leeuwarden", "Nederland"], ["Delft", "Nederland"], ["Deventer", "Nederland"], ["Alkmaar", "Nederland"], ["Venlo", "Nederland"], ["Hilversum", "Nederland"], ["Hengelo", "Nederland"], ["Borne", "Nederland"], ["Oldenzaal", "Nederland"], ["Almelo", "Nederland"],
  ["Brussel", "België"], ["Antwerpen", "België"], ["Gent", "België"], ["Brugge", "België"], ["Luik", "België"], ["Leuven", "België"], ["Mechelen", "België"], ["Namur", "België"], ["Oostende", "België"],
  ["Luxembourg", "Luxemburg"], ["Esch-sur-Alzette", "Luxemburg"],
  ["Zurich", "Zwitserland"], ["Geneva", "Zwitserland"], ["Basel", "Zwitserland"], ["Bern", "Zwitserland"], ["Lausanne", "Zwitserland"], ["Lugano", "Zwitserland"], ["Lucerne", "Zwitserland"],
  ["Berlin", "Duitsland"], ["Hamburg", "Duitsland"], ["Munich", "Duitsland"], ["Cologne", "Duitsland"], ["Frankfurt", "Duitsland"], ["Dusseldorf", "Duitsland"], ["Stuttgart", "Duitsland"], ["Dortmund", "Duitsland"], ["Leipzig", "Duitsland"], ["Hannover", "Duitsland"], ["Nuremberg", "Duitsland"], ["Bremen", "Duitsland"], ["Dresden", "Duitsland"], ["Bonn", "Duitsland"], ["Munster", "Duitsland"], ["Aachen", "Duitsland"], ["Karlsruhe", "Duitsland"], ["Freiburg", "Duitsland"],
  ["Paris", "Frankrijk"], ["Lyon", "Frankrijk"], ["Marseille", "Frankrijk"], ["Nice", "Frankrijk"], ["Toulouse", "Frankrijk"], ["Bordeaux", "Frankrijk"], ["Lille", "Frankrijk"], ["Nantes", "Frankrijk"], ["Strasbourg", "Frankrijk"], ["Montpellier", "Frankrijk"], ["Rennes", "Frankrijk"], ["Grenoble", "Frankrijk"], ["Cannes", "Frankrijk"], ["Biarritz", "Frankrijk"],
  ["London", "Verenigd Koninkrijk"], ["Manchester", "Verenigd Koninkrijk"], ["Birmingham", "Verenigd Koninkrijk"], ["Liverpool", "Verenigd Koninkrijk"], ["Edinburgh", "Verenigd Koninkrijk"], ["Glasgow", "Verenigd Koninkrijk"], ["Bristol", "Verenigd Koninkrijk"], ["Leeds", "Verenigd Koninkrijk"], ["Cardiff", "Verenigd Koninkrijk"], ["Belfast", "Verenigd Koninkrijk"],
  ["Dublin", "Ierland"], ["Cork", "Ierland"], ["Galway", "Ierland"], ["Limerick", "Ierland"],
  ["Madrid", "Spanje"], ["Barcelona", "Spanje"], ["Valencia", "Spanje"], ["Sevilla", "Spanje"], ["Bilbao", "Spanje"], ["Malaga", "Spanje"], ["Alicante", "Spanje"], ["Palma de Mallorca", "Spanje"], ["Granada", "Spanje"], ["San Sebastian", "Spanje"], ["Ibiza", "Spanje"],
  ["Lisbon", "Portugal"], ["Porto", "Portugal"], ["Faro", "Portugal"], ["Coimbra", "Portugal"], ["Braga", "Portugal"], ["Funchal", "Portugal"],
  ["Rome", "Italië"], ["Milan", "Italië"], ["Venice", "Italië"], ["Florence", "Italië"], ["Naples", "Italië"], ["Bologna", "Italië"], ["Turin", "Italië"], ["Palermo", "Italië"], ["Catania", "Italië"], ["Verona", "Italië"], ["Pisa", "Italië"], ["Bari", "Italië"], ["Cagliari", "Italië"],
  ["Vienna", "Oostenrijk"], ["Salzburg", "Oostenrijk"], ["Innsbruck", "Oostenrijk"], ["Graz", "Oostenrijk"], ["Linz", "Oostenrijk"],
  ["Copenhagen", "Denemarken"], ["Aarhus", "Denemarken"], ["Odense", "Denemarken"], ["Aalborg", "Denemarken"],
  ["Stockholm", "Zweden"], ["Gothenburg", "Zweden"], ["Malmo", "Zweden"], ["Uppsala", "Zweden"],
  ["Oslo", "Noorwegen"], ["Bergen", "Noorwegen"], ["Trondheim", "Noorwegen"], ["Stavanger", "Noorwegen"],
  ["Helsinki", "Finland"], ["Tampere", "Finland"], ["Turku", "Finland"], ["Oulu", "Finland"],
  ["Reykjavik", "IJsland"], ["Akureyri", "IJsland"],
  ["Warsaw", "Polen"], ["Krakow", "Polen"], ["Gdansk", "Polen"], ["Wroclaw", "Polen"], ["Poznan", "Polen"], ["Lodz", "Polen"], ["Katowice", "Polen"],
  ["Prague", "Tsjechië"], ["Brno", "Tsjechië"], ["Ostrava", "Tsjechië"], ["Pilsen", "Tsjechië"],
  ["Budapest", "Hongarije"], ["Debrecen", "Hongarije"], ["Szeged", "Hongarije"],
  ["Bratislava", "Slowakije"], ["Kosice", "Slowakije"],
  ["Ljubljana", "Slovenië"], ["Maribor", "Slovenië"], ["Bled", "Slovenië"],
  ["Zagreb", "Kroatië"], ["Split", "Kroatië"], ["Dubrovnik", "Kroatië"], ["Zadar", "Kroatië"], ["Rijeka", "Kroatië"],
  ["Belgrade", "Servië"], ["Novi Sad", "Servië"], ["Sarajevo", "Bosnië en Herzegovina"], ["Mostar", "Bosnië en Herzegovina"], ["Podgorica", "Montenegro"], ["Kotor", "Montenegro"], ["Tirana", "Albanië"],
  ["Athens", "Griekenland"], ["Thessaloniki", "Griekenland"], ["Heraklion", "Griekenland"], ["Rhodes", "Griekenland"], ["Chania", "Griekenland"],
  ["Istanbul", "Turkije"], ["Ankara", "Turkije"], ["Izmir", "Turkije"], ["Antalya", "Turkije"], ["Bodrum", "Turkije"],
  ["Bucharest", "Roemenië"], ["Cluj-Napoca", "Roemenië"], ["Timisoara", "Roemenië"], ["Brasov", "Roemenië"],
  ["Sofia", "Bulgarije"], ["Plovdiv", "Bulgarije"], ["Varna", "Bulgarije"], ["Burgas", "Bulgarije"],
  ["Riga", "Letland"], ["Tallinn", "Estland"], ["Vilnius", "Litouwen"], ["Kaunas", "Litouwen"],
  ["Valletta", "Malta"], ["Sliema", "Malta"], ["Nicosia", "Cyprus"], ["Larnaca", "Cyprus"], ["Limassol", "Cyprus"]
].map(([city, country]) => ({ city, country }));

window.meetwayEuropeCities.push(...[
  ["Rijssen", "Nederland"], ["Delden", "Nederland"], ["Haaksbergen", "Nederland"], ["Lochem", "Nederland"], ["Winterswijk", "Nederland"], ["Doetinchem", "Nederland"], ["Gouda", "Nederland"], ["Woerden", "Nederland"], ["Hoorn", "Nederland"], ["Sneek", "Nederland"], ["Drachten", "Nederland"], ["Assen", "Nederland"], ["Meppel", "Nederland"], ["Roermond", "Nederland"], ["Sittard", "Nederland"], ["Valkenburg", "Nederland"], ["Middelburg", "Nederland"], ["Goes", "Nederland"], ["Harderwijk", "Nederland"], ["Ede", "Nederland"],
  ["Kortrijk", "Belgie"], ["Hasselt", "Belgie"], ["Genk", "Belgie"], ["Tournai", "Belgie"], ["Ypres", "Belgie"], ["Knokke-Heist", "Belgie"], ["Dinant", "Belgie"], ["Spa", "Belgie"], ["Durbuy", "Belgie"],
  ["Winterthur", "Zwitserland"], ["St. Gallen", "Zwitserland"], ["Thun", "Zwitserland"], ["Interlaken", "Zwitserland"], ["Zug", "Zwitserland"], ["Biel", "Zwitserland"], ["Montreux", "Zwitserland"], ["Sion", "Zwitserland"], ["Chur", "Zwitserland"],
  ["Heidelberg", "Duitsland"], ["Trier", "Duitsland"], ["Regensburg", "Duitsland"], ["Rothenburg ob der Tauber", "Duitsland"], ["Koblenz", "Duitsland"], ["Lubeck", "Duitsland"], ["Potsdam", "Duitsland"], ["Konstanz", "Duitsland"], ["Augsburg", "Duitsland"], ["Mainz", "Duitsland"], ["Wurzburg", "Duitsland"], ["Fussen", "Duitsland"],
  ["Annecy", "Frankrijk"], ["Avignon", "Frankrijk"], ["Aix-en-Provence", "Frankrijk"], ["Colmar", "Frankrijk"], ["Reims", "Frankrijk"], ["Dijon", "Frankrijk"], ["La Rochelle", "Frankrijk"], ["Saint-Malo", "Frankrijk"], ["Perpignan", "Frankrijk"], ["Carcassonne", "Frankrijk"], ["Arles", "Frankrijk"], ["Chamonix", "Frankrijk"],
  ["Cambridge", "Verenigd Koninkrijk"], ["Oxford", "Verenigd Koninkrijk"], ["Bath", "Verenigd Koninkrijk"], ["York", "Verenigd Koninkrijk"], ["Brighton", "Verenigd Koninkrijk"], ["Canterbury", "Verenigd Koninkrijk"], ["St Andrews", "Verenigd Koninkrijk"], ["Inverness", "Verenigd Koninkrijk"],
  ["Sitges", "Spanje"], ["Girona", "Spanje"], ["Tarragona", "Spanje"], ["Toledo", "Spanje"], ["Salamanca", "Spanje"], ["Cordoba", "Spanje"], ["Cadiz", "Spanje"], ["Ronda", "Spanje"], ["Marbella", "Spanje"], ["Nerja", "Spanje"],
  ["Sintra", "Portugal"], ["Aveiro", "Portugal"], ["Evora", "Portugal"], ["Lagos", "Portugal"], ["Cascais", "Portugal"], ["Guimaraes", "Portugal"],
  ["Siena", "Italie"], ["Lucca", "Italie"], ["Ravenna", "Italie"], ["Parma", "Italie"], ["Modena", "Italie"], ["Bergamo", "Italie"], ["Como", "Italie"], ["Sorrento", "Italie"], ["Matera", "Italie"], ["Lecce", "Italie"],
  ["Cesky Krumlov", "Tsjechie"], ["Karlovy Vary", "Tsjechie"], ["Sopot", "Polen"], ["Zakopane", "Polen"], ["Pecs", "Hongarije"], ["Eger", "Hongarije"], ["Tartu", "Estland"], ["Klaipeda", "Litouwen"],
  ["Rovinj", "Kroatie"], ["Pula", "Kroatie"], ["Hvar", "Kroatie"], ["Trogir", "Kroatie"], ["Koper", "Slovenie"], ["Piran", "Slovenie"], ["Ohrid", "Noord-Macedonie"], ["Berat", "Albanie"]
].map(([city, country]) => ({ city, country })));
